[tool.poetry]
name = "community-be"
version = "0.1.0"
description = "FastAPI Community Backend"
authors = [
    "bina <you@example.com>"
]
license = "MIT"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.122.0,<0.123.0"
python-dotenv = ">=1.2.1,<2.0.0"
python-multipart = ">=0.0.20,<0.0.21"
python-jose = ">=3.5.0,<4.0.0"
bcrypt = ">=5.0.0,<6.0.0"
ultralytics = ">=8.3.231,<9.0.0"
sqlalchemy = "^2.0.44"
mysql-connector-python = "^9.5.0"

[tool.poetry.group.dev.dependencies]
uvicorn = ">=0.38.0,<0.39.0"


[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
